### ISSUE TITLE
Not everything is translated in my shop

### ISSUE THREAD

**Issue by NielN98** [gizmecano/opencart-2-fr#1]
There are a few things not translated. Like decimal_point, button_cart ... 
It is in the backend and in the frontend.

You can check it: http://xn--botes-aux-lettres-wvb.be/

**Comment by GizMecano** [comment]
Firstly, the value of the variable `decimal_point` doesn't normally have to be _translated_ because it should display a `,` symbol (you can see this in the [`default.php`](https://github.com/GizMecano/opencart-2-fr/blob/6c561fb3655a3b0bd7fbe985a0e6da897257fa00/catalog/language/fr-FR/default.php#L23) file on the `catalog` folder for example).

Next, the variable `button_cart` only appears one time in the [`default.php`](https://github.com/GizMecano/opencart-2-fr/blob/6c561fb3655a3b0bd7fbe985a0e6da897257fa00/catalog/language/fr-FR/default.php#L38) file of the `catalog` section and it is properly translated as `'Ajouter au panier'`...

So, I think the problem can come either from the version of OpenCart you are using (this translation is currently only compatible until the [version 2.0.1.1](https://github.com/GizMecano/opencart-2-fr#compatibility)), or from the theme you have installed.

Can you precise the exact version of OpenCart you have installed? Concerning the theme, can you paste an sample of the code where the button_cart variable should normally be displayed, for example (from `product.tpl` file in the default theme):

```php
<button type="button" id="button-cart" data-loading-text="<?php echo $text_loading; ?>" class="btn btn-primary btn-lg btn-block">
  <?php echo $button_cart; ?>
</button>
```

**Comment by NielN98** [comment]
I'm using Opencart version 2.0.3.1. Do you have a French package for this version?

**Comment by GizMecano** [comment]
Not at all.
As I wrote above (and as it is mentioned in the [`readme.md`](https://github.com/GizMecano/opencart-2-fr#compatibility)), this localization is currently only compatible till the version 2.0.1.1.
I have not yet planned to check changes for upgrading compatibility with later versions.

**Comment by NielN98** [comment]
I don't think the Opencart version is the problem here, because the translations are present, but it will not run. Very strange ...

**Comment by GizMecano** [comment]
It is indeed a possibility and that is why I wrote:

> Concerning the theme, can you paste a sample of the code where the `button_cart` variable should normally be displayed (...)?

Without the availability to check the code of your theme, I can't tell you more at this time.

**Comment by NielN98** [comment]
I know what the problem is. Everything what is in the default.php, is not translated.

**Comment by NielN98** [comment]
I found it: I have renamed default.php to fr-FR.php and now it's works. Thanks for your comment!

**Comment by GizMecano** [comment]
Effectively, this is the solution: according to [this issue](https://github.com/opencart/opencart/issues/2866), the name of `default.php` file has changed since version 2.0.2.0.
